-- Eartharmony - Supplier and Products Upload
-- Run this entire script in Supabase SQL Editor (single execution)

WITH new_supplier AS (
  INSERT INTO suppliers (name, description, image, location, category, lat, lng, status, email, instagram)
  VALUES (
    'Eartharmony',
    'Eartharmony is a community-owned co-operative refill shop on Queen Street in Belper. They stock organic and plastic-free dry goods, herbs, spices, teas, snacks and cleaning products from ethical brands like Suma, Tree Harvest, Ecoleaf and Alter/native — sold loose and refilled into your own containers.',
    '',
    '2 Queen Street, Belper, Derbyshire, DE56 1NR',
    'Refill Shop',
    53.0285,
    -1.4749,
    'launch_not_live',
    'hello@eartharmony.online',
    NULL
  )
  RETURNING id
)
INSERT INTO products (supplier_id, name, description, price, unit, image, category, in_stock, locality, lat, lng, variable_location, status, allergens, tags)
SELECT id, name, description, price, unit, '', category, true, locality, lat, lng, variable_location, 'approved', allergens, tags
FROM new_supplier, (VALUES
  ('Darjeeling Earl Grey', 'Priced per 10g organic. Mature aromatic Darjeeling with rich bergamot flavouring.', 2.4, '30g', 'Drinks', 'UK', 53.74, -2.0, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Earl Grey tea - naturally decaffeinated', 'Priced per 10g organic. Naturally decaffeinated Ceylon, soft infusion, soft tangy taste.', 2.7, '30g', 'Drinks', 'UK', 53.74, -2.0, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Green Sencha Tea', 'Priced per 10g. Green tea harvested in early spring, steamed leaves, dark vibrant olive green.', 1.68, '30g', 'Drinks', 'UK', 53.74, -2.0, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'vegan', 'vegetarian']),
  ('Nilgiri Assam', 'Priced per 10 g organic and plastic free. Fine tea from south India, fresh slightly grassy.', 2.01, '30g', 'Drinks', 'UK', 53.74, -2.0, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Bicarbonate of soda', 'Bicarbonate of soda (baking soda) for baking or home cleaning. Priced per 100g.', 0.38, '30g', 'Other', 'Local', 52.804, -1.642, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Citric Acid', 'Food grade citric acid, biodegradable household basic.', 0.38, '30g', 'Other', 'Local', 52.804, -1.642, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Clear and Simple Body Wash 500ml', '500 ml in Boston style amber PET bottle. £2 deposit included. Exceptionally mild, ideal for sensitive skin.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Clear and Simple Conditioner 500 ml', '500 ml in Boston style amber PET bottle. £2 deposit included. Sensitive/all hair types.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Clear and Simple Shampoo 500 ml', '500 ml in Boston style amber PET bottle. £2 deposit included. Sensitive/all hair types.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Coconut Conditioner 500 ml', '500 ml in amber Boston-style PET bottle. £2 deposit included. Normal/Dry Hair tropical blend.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY['nuts'], ARRAY[]::text[]),
  ('Coconut Shampoo 500 ml', '500 ml in Boston style amber PET bottle. £2 deposit included. Normal/dry hair tropical blend.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY['nuts'], ARRAY[]::text[]),
  ('Ecoleaf Citrus Washing Up Liquid - 5 litres', 'Effective yet gentle Ecoleaf washing up liquid from sustainably sourced plant materials, fully biodegradable. 5 litre containers.', 14.65, '5000ml', 'Other', 'UK', 52.486, -1.89, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Lavender & Geranium Body Wash 500 ml', '500 ml in Boston style amber PET bottle. £2 deposit included.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Lavender & Geranium Conditioner 500 ml', '500ml For Normal/Dry Hair. Lavender and geranium classic combination.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Lavender & Geranium Shampoo 500 ml', '500ml in Boston style amber PET bottle. £2 deposit included.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Liquid Hand Soap 500 ml', 'Organic walnut halves priced per 100g.', 4.15, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY['organic']),
  ('Rose & Geranium Body Wash 500ml', '500 ml in Boston style amber PET bottle. £2 deposit included. Floral conditioner.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Rose & Geranium Shampoo', '500 ml in Boston style amber PET bottle with aluminium cap. £2 deposit included. Flat-out floral with classic bouquet.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Sodium Carbonate Soda Crystals', 'Priced per 100g popular multi-purpose cleaner.', 0.06, '30g', 'Other', 'Local', 52.804, -1.642, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Tea Tree Body Wash 500 ml', '500 ml in a quality Boston style amber PET bottle with aluminium cap. £2 deposit included. Antiseptic tea tree, nourishing body wash.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Tea Tree Conditioner 500ml', '500 ml in Boston style amber PET bottle. £2 deposit included. Normal/Oily hair antiseptic tea tree.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Tea Tree Shampoo', '500 ml in Boston style amber PET bottle. £2 deposit included. Normal/oily hair, antiseptic tea tree.', 6.4, '500ml', 'Other', 'UK', 52.0, -2.0, false, ARRAY[]::text[], ARRAY[]::text[]),
  ('Andrographis', 'Andrographis priced per 10g organic.', 7.5, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Arborio Rice', 'Priced per 100g This is an organic product.', 16.8, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Ashwaganda Root Powder', 'Ashwaganda root powder priced per 10g organic.', 7.5, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Brahmi', 'Priced per 10g. This is Organic product.', 1.68, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Brown Basmati Rice', 'Priced per 100g This is an organic product.', 0.1, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Brown Lentils', 'Priced per 100g This is an organic product.', 0.98, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Buckwheat', 'Priced per 100g This is an organic product.', 1.0, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Cane Sugar', 'Priced per 100g organic Essential Organic Cane sugar, raw sugar, delicate molasses taste.', 1.32, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Cashews', 'Priced per 100g organic raw unsalted whole cashews.', 3.9, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['nuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Caster Sugar', 'Priced per 100g organic and plastic-free caster sugar.', 1.22, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Cayenne Pepper', 'Cayenne Pepper from Suma — refilled at the shop in Belper.', 10.8, '30g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'vegan', 'vegetarian']),
  ('Chaga Mushroom Powder', 'Priced per 100g. This is Organic product.', 2.28, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Chamomile', 'Priced per 10g organic product. Chamomile tea is a popular beverage with health benefits.', 17.4, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Chia Seeds', 'Priced per 100g organic product.', 2.2, '200g', 'Pantry', 'Local', 52.804, -1.642, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Cinnamon (ground) 10g', 'Priced per 10 g organic product supplied by Tree-Harvest. Zeylanicum ''true cinnamon'' has a sweeter, more refined flavour.', 0.99, '30g', 'Pantry', 'UK', 51.45, -2.59, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Cinnamon (sticks)', 'Beechtree cinnamon sticks.', 7.38, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'vegan', 'vegetarian']),
  ('Cloves (whole)', 'Whole cloves priced per 10g.', 1.95, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Coconut chips', 'Priced per 100 g organic. Coconut chips great for granola, snacks, sweet or savoury dishes.', 1.8, '200g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY['nuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Coriander seeds', 'Priced per 10 g This is an organic product.', 0.84, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Cranberries', 'Priced per 100g. This product is organic.', 3.36, '200g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Cumin seeds', 'Priced per 10 g organic.', 1.26, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Damiana', 'Priced per 10g. This is Organic product.', 1.5, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Deluxe Muesli', 'A fully organic, high quality muesli with dates. Ingredients: oats, sultanas, malted wheat flakes, barley flakes, wheat flakes, sunflower seeds, dates, apricots.', 1.0, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Echinacea leaves and flowers', 'Echinacea leaves and flowers priced per 10g organic.', 1.44, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Elderberries', 'Priced per 10g. Elderberries are rich in flavonoids and anthocyanins.', 1.62, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'vegan', 'vegetarian']),
  ('Ginger (ground)', 'Priced per 10 g organic and plastic free.', 1.02, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Goji berries', 'Priced per 100g organic product.', 0.75, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Granola', 'Ingredients: Oats, Sugar, Barley, Sunflower Oil, Desiccated Coconut, Cane Molasses, Glucose Syrup, Barley Malt Extract, Natural Flavouring, Cinnamon.', 4.16, '200g', 'Pantry', 'UK', 51.45, -2.59, false, ARRAY['gluten'], ARRAY['dairy-free', 'vegan', 'vegetarian']),
  ('Green Cardamom (whole)', 'Priced per 10 g organic.', 3.0, '30g', 'Pantry', 'UK', 51.45, -2.59, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Green Lentils', 'Priced per 100g organic product.', 1.0, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Hazelnuts', 'Priced per 100g organic product.', 5.36, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['nuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Hemp Leaves', 'Priced per 10g. This product is Organic.', 1.8, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Hemp Seeds', 'Priced per 100g organic product.', 1.54, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Hibiscus', 'Priced per 10g organic. Hibiscus tea used historically as a remedy and a diuretic.', 0.9, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Irish Moss 10g', 'Priced per 10g. This is Organic product.', 2.88, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Jumbo Oats', 'Organic jumbo oats priced per 100g.', 0.58, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Marjoram', 'Marjoram herb. Priced per 10g.', 0.72, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Mixed Spice', 'Priced per 10 g organic and plastic-free.', 0.78, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Mung Beans', 'Priced per 100g This is an organic and plastic-free product.', 1.22, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Mustard Seed (black)', 'Priced per 10 g organic.', 0.72, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY['mustard'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Mustard Seed (yellow)', 'Priced per 10 g This is an organic and plastic-free product.', 0.72, '30g', 'Pantry', 'International', 52.0, 8.0, false, ARRAY['mustard'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Nutritional Yeast Flakes', 'Wholegrain rolled oats.', 6.6, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['nuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Oatstraw', 'Priced per 10g. This is Organic product.', 1.5, '30g', 'Pantry', 'Local', 52.804, -1.642, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Oregano', 'Priced per 10 g This is an organic and plastic free product.', 1.35, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Organic Bouillon', 'Priced per 100g organic Marigold Vegetable Bouillon, Swiss recipe, gluten free, fairly traded.', 0.35, '30g', 'Pantry', 'International', 47.0, 8.0, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Parsley Leaf', 'Priced per 10 g organic. Parsley leaf infusion is underrated.', 1.68, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Peanuts', 'Priced per 100g This is an organic product.', 1.76, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['nuts', 'peanuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Pecan Nuts', 'Priced per 100g organic product.', 7.0, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['nuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Peppermint Leaves', 'Priced per 10 g organic and plastic free. Peppermint tea offers several health benefits.', 1.35, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Pine Nut Kernels', 'Pine nut kernels. Priced per 10g.', 2.1, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY['nuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Pitted Deglet Noor Dates', 'Priced per 100g organic. Deglet Noor dates are semi-dry, slightly crunchy with sweet flavour.', 2.0, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Popping Corn', 'Popping corn priced per 100g.', 0.74, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Porridge Oats refills', 'Priced per 100 g organic product.', 0.58, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Prunes', 'Priced per 100g organic product.', 3.1, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Raisins', 'Organic almonds priced per 100g.', 2.0, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Red Lentils', 'Priced per 100g organic and plastic free product.', 0.76, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Reishi Mushroom Powder 10g', 'Priced per 10g. This is Organic product.', 1.98, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Roasted and Salted Peanuts', 'Priced per 100g This is an organic and plastic free product.', 1.7, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['nuts', 'peanuts'], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Rosehips', 'Priced per 10g. This is Organic product.', 2.4, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Rosemary', 'Priced per 10 g organic and plastic free. Rosemary with potent woody scent, flavouring for potatoes, soups, teas.', 0.99, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Sage', 'Priced per 10 g organic and plastic free. Strong sage flavour, added early in cooking.', 1.2, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Spearmint', 'Priced per 10 g organic and plastic free. Spearmint leaves naturally caffeine-free, refreshing hot or cold.', 1.26, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Spirulina Powder', 'Priced per 100 g organic and plastic free. Organic Spirulina Powder, ancient blue-green algae packed with plant nutrients.', 1.02, '30g', 'Pantry', 'UK', 51.5, -2.5, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('St. John''s Wort', 'St. John''s Wort priced per 10g organic.', 0.81, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Sultanas', 'Priced per 100g organic sultanas, sweet baking ingredient.', 1.42, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Sunflower Seeds', 'Organic sunflower seeds priced per 100g.', 2.44, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Thyme', 'Thyme priced per 10g organic.', 0.78, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Tulsi (Holy Basil)', 'Tulsi (Holy Basil) priced per 10g.', 1.2, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Turmeric', 'Beechtree turmeric per 10g, earthy spice, deep orange hue.', 0.84, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'vegan', 'vegetarian']),
  ('Unrefined Coarse Sea Salt', 'Unrefined coarse sea salt priced per 100g.', 0.06, '30g', 'Pantry', 'Local', 52.804, -1.642, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'vegan', 'vegetarian']),
  ('Unrefined Fine Sea Salt', 'Unrefined fine sea salt refill. Priced per 100g.', 0.06, '30g', 'Pantry', 'Local', 52.804, -1.642, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'vegan', 'vegetarian']),
  ('Valerian Root', 'Valerian root priced per 10g organic.', 2.1, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('White Basmati Rice', 'Priced per 100g organic white basmati rice.', 1.0, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('White Fusilli', 'White fusilli pasta priced per 100g. Italian organic pasta by Iris Bio.', 0.68, '200g', 'Pantry', 'International', 45.5, 9.5, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('White Orzo', 'Priced per 100g organic product.', 0.94, '200g', 'Pantry', 'UK', 51.45, -2.59, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('White Penne', '100g organic Italian penne pasta by Iris Bio in Lombardy.', 0.72, '200g', 'Pantry', 'International', 45.5, 9.5, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('White Spaghetti', '100g organic Italian white spaghetti by Iris Bio in Lombardy.', 0.72, '200g', 'Pantry', 'International', 45.5, 9.5, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Whole Black Peppercorns', 'Organic linseeds priced per 100g.', 1.32, '30g', 'Pantry', 'UK', 51.5, -0.13, false, ARRAY[]::text[], ARRAY['dairy-free', 'gluten-free', 'organic', 'vegan', 'vegetarian']),
  ('Wholemeal Couscous', 'Priced per 100g organic and plastic free wholewheat flour.', 0.8, '200g', 'Pantry', 'UK', 53.717, -2.012, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Wholewheat Fusilli', 'Priced per 100g organic and plastic free. Italian organic pasta by Iris Bio in Lombardy, Italy.', 0.72, '200g', 'Pantry', 'International', 45.5, 9.5, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Wholewheat Penne', 'Priced per 100g organic and plastic free. Italian organic pasta by Iris Bio in Lombardy, Italy.', 0.72, '200g', 'Pantry', 'International', 45.5, 9.5, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian']),
  ('Wholewheat Spaghetti', 'Priced per 100g organic and plastic free. Italian organic pasta by Iris Bio in Lombardy, Italy, bronze die extruded.', 0.72, '200g', 'Pantry', 'International', 45.5, 9.5, false, ARRAY['gluten'], ARRAY['dairy-free', 'organic', 'vegan', 'vegetarian'])
) AS p(name, description, price, unit, category, locality, lat, lng, variable_location, allergens, tags);
